# Generated by Django 3.1.2 on 2020-10-11 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=50, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
