# Generated by Django 3.1.2 on 2020-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201014_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='EID'),
        ),
    ]
